-- Transaction-sealed source snapshots for artifact-reference projection v2.
--
-- This migration is additive and grants no runtime execution, retention,
-- release, deletion, provider-operation, or cost authority. Migration 0058
-- remains fixture-only and incomplete. A future trusted D1 executor must claim
-- an attempt, read and recheck every source set atomically, insert the receipt,
-- and reload the exact committed row before any caller may trust completeness.

CREATE TABLE "RevenueArtifactReferenceSnapshotAttempt" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "attemptVersion" TEXT NOT NULL,
  "workflowRunId" TEXT NOT NULL,
  "businessId" TEXT NOT NULL,
  "lineageRootManifestId" TEXT NOT NULL,
  "attemptNumber" INTEGER NOT NULL,
  "fencingToken" INTEGER NOT NULL,
  "ownerId" TEXT NOT NULL,
  "queryContractVersion" TEXT NOT NULL,
  "queryContractDigest" TEXT NOT NULL,
  "requestDigest" TEXT NOT NULL,
  "requestedAt" DATETIME NOT NULL,
  "acquiredAt" DATETIME NOT NULL,
  "expiresAt" DATETIME NOT NULL,
  "mode" TEXT NOT NULL,
  "executorKind" TEXT NOT NULL,
  "attemptDigest" TEXT NOT NULL,
  "attemptJson" TEXT NOT NULL,
  "providerOperationsAuthorized" INTEGER NOT NULL,
  "releaseAuthorized" INTEGER NOT NULL,
  "deletionAuthorized" INTEGER NOT NULL,
  "costAuthorizedUsd" REAL NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ("attemptVersion" = 'artifact-reference-snapshot-attempt-v1'),
  CHECK ("attemptNumber" >= 1 AND "attemptNumber" <= 10000),
  CHECK ("fencingToken" >= 1 AND "fencingToken" <= 2147483647),
  CHECK (julianday("acquiredAt") >= julianday("requestedAt")),
  CHECK (julianday("expiresAt") > julianday("acquiredAt")),
  CHECK (unixepoch("expiresAt") - unixepoch("acquiredAt") <= 300),
  CHECK ("mode" = 'SHADOW'),
  CHECK ("executorKind" = 'D1_ATOMIC_BATCH'),
  CHECK (length("queryContractDigest") = 64 AND "queryContractDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("requestDigest") = 64 AND "requestDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("attemptDigest") = 64 AND "attemptDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid("attemptJson")),
  CHECK ("providerOperationsAuthorized" = 0),
  CHECK ("releaseAuthorized" = 0),
  CHECK ("deletionAuthorized" = 0),
  CHECK ("costAuthorizedUsd" = 0),
  FOREIGN KEY ("workflowRunId") REFERENCES "RevenueWorkflowRun" ("id") ON DELETE RESTRICT,
  FOREIGN KEY ("businessId") REFERENCES "RevenueBusiness" ("id") ON DELETE RESTRICT,
  FOREIGN KEY ("lineageRootManifestId") REFERENCES "RevenueArtifactManifest" ("id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "RevenueArtifactReferenceSnapshotAttempt_root_attempt_key" ON "RevenueArtifactReferenceSnapshotAttempt" ("lineageRootManifestId", "attemptNumber");
CREATE UNIQUE INDEX "RevenueArtifactReferenceSnapshotAttempt_root_fence_key" ON "RevenueArtifactReferenceSnapshotAttempt" ("lineageRootManifestId", "fencingToken");
CREATE UNIQUE INDEX "RevenueArtifactReferenceSnapshotAttempt_digest_key" ON "RevenueArtifactReferenceSnapshotAttempt" ("attemptDigest");
CREATE INDEX "RevenueArtifactReferenceSnapshotAttempt_root_acquired_idx" ON "RevenueArtifactReferenceSnapshotAttempt" ("lineageRootManifestId", "acquiredAt");

CREATE TABLE "RevenueArtifactManifestAvailabilityReceipt" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "availabilityVersion" TEXT NOT NULL,
  "manifestId" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "checkedAt" DATETIME NOT NULL,
  "validThrough" DATETIME NOT NULL,
  "expiresAt" DATETIME,
  "checkerKind" TEXT NOT NULL,
  "objectSetDigest" TEXT NOT NULL,
  "receiptDigest" TEXT NOT NULL,
  "receiptJson" TEXT NOT NULL,
  "providerReadPerformed" INTEGER NOT NULL,
  "providerOperationsAuthorized" INTEGER NOT NULL,
  "releaseAuthorized" INTEGER NOT NULL,
  "deletionAuthorized" INTEGER NOT NULL,
  "costUsd" REAL NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ("availabilityVersion" = 'artifact-manifest-availability-v2'),
  CHECK ("state" IN ('VERIFIED_PRESENT', 'MISSING', 'UNKNOWN')),
  CHECK (julianday("validThrough") >= julianday("checkedAt")),
  CHECK ("checkerKind" IN ('FIXTURE', 'R2_HEAD')), 
  CHECK (("checkerKind" = 'FIXTURE' AND "providerReadPerformed" = 0)
    OR ("checkerKind" = 'R2_HEAD' AND "providerReadPerformed" = 1)),
  CHECK (length("objectSetDigest") = 64 AND "objectSetDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("receiptDigest") = 64 AND "receiptDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid("receiptJson")),
  CHECK ("providerOperationsAuthorized" = 0),
  CHECK ("releaseAuthorized" = 0),
  CHECK ("deletionAuthorized" = 0),
  CHECK ("costUsd" = 0),
  FOREIGN KEY ("manifestId") REFERENCES "RevenueArtifactManifest" ("id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "RevenueArtifactManifestAvailabilityReceipt_observation_key" ON "RevenueArtifactManifestAvailabilityReceipt" ("manifestId", "availabilityVersion", "checkedAt", "checkerKind");
CREATE UNIQUE INDEX "RevenueArtifactManifestAvailabilityReceipt_digest_key" ON "RevenueArtifactManifestAvailabilityReceipt" ("receiptDigest");
CREATE INDEX "RevenueArtifactManifestAvailabilityReceipt_manifest_checked_idx" ON "RevenueArtifactManifestAvailabilityReceipt" ("manifestId", "checkedAt");

CREATE TABLE "RevenueArtifactReferenceCompletenessReceipt" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "receiptVersion" TEXT NOT NULL,
  "snapshotAttemptId" TEXT NOT NULL,
  "workflowRunId" TEXT NOT NULL,
  "businessId" TEXT NOT NULL,
  "lineageRootManifestId" TEXT NOT NULL,
  "attemptNumber" INTEGER NOT NULL,
  "fencingToken" INTEGER NOT NULL,
  "queryContractVersion" TEXT NOT NULL,
  "queryContractDigest" TEXT NOT NULL,
  "snapshotCapturedAt" DATETIME NOT NULL,
  "freshUntil" DATETIME NOT NULL,
  "workflowRunCount" INTEGER NOT NULL,
  "workflowHistoryCount" INTEGER NOT NULL,
  "manifestCount" INTEGER NOT NULL,
  "manifestItemCount" INTEGER NOT NULL,
  "promotionCount" INTEGER NOT NULL,
  "promotionUseCount" INTEGER NOT NULL,
  "manifestUseCount" INTEGER NOT NULL,
  "evidenceUseCount" INTEGER NOT NULL,
  "useEndCount" INTEGER NOT NULL,
  "availabilityCount" INTEGER NOT NULL,
  "sourceSetProofsDigest" TEXT NOT NULL,
  "sourceSetProofsJson" TEXT NOT NULL,
  "sourceFactsDigest" TEXT NOT NULL,
  "receiptDigest" TEXT NOT NULL,
  "receiptJson" TEXT NOT NULL,
  "completenessAssurance" TEXT NOT NULL,
  "availabilityAssurance" TEXT NOT NULL,
  "snapshotComplete" INTEGER NOT NULL,
  "committedAndReloaded" INTEGER NOT NULL,
  "retentionConclusionAuthorized" INTEGER NOT NULL,
  "projectionPersistenceAuthorized" INTEGER NOT NULL,
  "providerOperationsAuthorized" INTEGER NOT NULL,
  "releaseAuthorized" INTEGER NOT NULL,
  "deletionAuthorized" INTEGER NOT NULL,
  "costAuthorizedUsd" REAL NOT NULL,
  "recordedAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ("receiptVersion" = 'artifact-reference-completeness-receipt-v1'),
  CHECK ("attemptNumber" >= 1 AND "attemptNumber" <= 10000),
  CHECK ("fencingToken" >= 1 AND "fencingToken" <= 2147483647),
  CHECK (julianday("freshUntil") >= julianday("snapshotCapturedAt")),
  CHECK (unixepoch("freshUntil") - unixepoch("snapshotCapturedAt") <= 300),
  CHECK (julianday("recordedAt") >= julianday("snapshotCapturedAt")),
  CHECK ("workflowRunCount" = 1),
  CHECK ("workflowHistoryCount" >= 1 AND "workflowHistoryCount" <= 5000),
  CHECK ("manifestCount" >= 1 AND "manifestCount" <= 100),
  CHECK ("manifestItemCount" >= 1 AND "manifestItemCount" <= 500),
  CHECK ("promotionCount" >= 0 AND "promotionCount" <= 200),
  CHECK ("promotionUseCount" >= 0 AND "promotionUseCount" <= 1000),
  CHECK ("manifestUseCount" >= 0 AND "manifestUseCount" <= 1000),
  CHECK ("evidenceUseCount" >= 0 AND "evidenceUseCount" <= 1000),
  CHECK ("useEndCount" >= 0 AND "useEndCount" <= 1000),
  CHECK ("availabilityCount" = "manifestCount"),
  CHECK (length("queryContractDigest") = 64 AND "queryContractDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("sourceSetProofsDigest") = 64 AND "sourceSetProofsDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("sourceFactsDigest") = 64 AND "sourceFactsDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("receiptDigest") = 64 AND "receiptDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid("sourceSetProofsJson")),
  CHECK (json_valid("receiptJson")),
  CHECK ("completenessAssurance" = 'D1_ATOMIC_RECHECK_AND_RELOAD'),
  CHECK ("availabilityAssurance" = 'R2_HEAD_PER_MANIFEST'),
  CHECK ("snapshotComplete" = 1),
  CHECK ("committedAndReloaded" = 1),
  CHECK ("retentionConclusionAuthorized" = 0),
  CHECK ("projectionPersistenceAuthorized" = 0),
  CHECK ("providerOperationsAuthorized" = 0),
  CHECK ("releaseAuthorized" = 0),
  CHECK ("deletionAuthorized" = 0),
  CHECK ("costAuthorizedUsd" = 0),
  FOREIGN KEY ("snapshotAttemptId") REFERENCES "RevenueArtifactReferenceSnapshotAttempt" ("id") ON DELETE RESTRICT,
  FOREIGN KEY ("workflowRunId") REFERENCES "RevenueWorkflowRun" ("id") ON DELETE RESTRICT,
  FOREIGN KEY ("businessId") REFERENCES "RevenueBusiness" ("id") ON DELETE RESTRICT,
  FOREIGN KEY ("lineageRootManifestId") REFERENCES "RevenueArtifactManifest" ("id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "RevenueArtifactReferenceCompletenessReceipt_attempt_key" ON "RevenueArtifactReferenceCompletenessReceipt" ("snapshotAttemptId");
CREATE UNIQUE INDEX "RevenueArtifactReferenceCompletenessReceipt_digest_key" ON "RevenueArtifactReferenceCompletenessReceipt" ("receiptDigest");
CREATE UNIQUE INDEX "RevenueArtifactReferenceCompletenessReceipt_root_snapshot_key" ON "RevenueArtifactReferenceCompletenessReceipt" ("lineageRootManifestId", "receiptVersion", "snapshotCapturedAt");
CREATE INDEX "RevenueArtifactReferenceCompletenessReceipt_root_recorded_idx" ON "RevenueArtifactReferenceCompletenessReceipt" ("lineageRootManifestId", "recordedAt");

CREATE TABLE "RevenueArtifactReferenceSourceSetProof" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "completenessReceiptId" TEXT NOT NULL,
  "setOrdinal" INTEGER NOT NULL,
  "setName" TEXT NOT NULL,
  "predicateVersion" TEXT NOT NULL,
  "rowCount" INTEGER NOT NULL,
  "setDigest" TEXT NOT NULL,
  "proofDigest" TEXT NOT NULL,
  "proofJson" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ("setOrdinal" >= 1 AND "setOrdinal" <= 15),
  CHECK ("setName" IN ('WORKFLOW_RUNS', 'WORKFLOW_DEFINITIONS', 'WORKFLOW_DELIVERIES', 'WORKFLOW_ATTEMPTS', 'WORKFLOW_LEASES', 'WORKFLOW_RECEIPT_REVISIONS', 'WORKFLOW_ATTEMPT_CLOSURES', 'MANIFESTS', 'MANIFEST_ITEMS', 'PROMOTIONS', 'PROMOTION_USES', 'MANIFEST_USES', 'EVIDENCE_USES', 'USE_ENDS', 'AVAILABILITY')),
  CHECK ("rowCount" >= 0 AND "rowCount" <= 5000),
  CHECK (length("setDigest") = 64 AND "setDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (length("proofDigest") = 64 AND "proofDigest" NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid("proofJson")),
  FOREIGN KEY ("completenessReceiptId") REFERENCES "RevenueArtifactReferenceCompletenessReceipt" ("id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "RevenueArtifactReferenceSourceSetProof_receipt_ordinal_key" ON "RevenueArtifactReferenceSourceSetProof" ("completenessReceiptId", "setOrdinal");
CREATE UNIQUE INDEX "RevenueArtifactReferenceSourceSetProof_receipt_name_key" ON "RevenueArtifactReferenceSourceSetProof" ("completenessReceiptId", "setName");
CREATE INDEX "RevenueArtifactReferenceSourceSetProof_digest_idx" ON "RevenueArtifactReferenceSourceSetProof" ("proofDigest");
